web: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
release: cd backend && python -m alembic upgrade head && python app/database/init_db.py
worker: cd backend && celery -A app.core.celery_app worker --loglevel=info