apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
  labels:
    app: financial-planner
    component: config
data:
  # Application Configuration
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  WORKERS: "4"
  MAX_CONNECTIONS: "100"
  
  # Database Configuration
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Cache Configuration
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_RETRY_ON_TIMEOUT: "true"
  CACHE_TTL: "3600"
  
  # Market Data Configuration
  MARKET_DATA_REFRESH_INTERVAL: "60"
  MARKET_DATA_CACHE_DURATION: "300"
  ENABLE_REAL_TIME_DATA: "true"
  
  # Monte Carlo Configuration
  DEFAULT_SIMULATIONS: "10000"
  MAX_SIMULATIONS: "100000"
  SIMULATION_BATCH_SIZE: "1000"
  
  # AI Configuration
  LLM_MAX_TOKENS: "4000"
  LLM_TEMPERATURE: "0.7"
  ENABLE_AI_FEATURES: "true"
  
  # Security Configuration
  TOKEN_EXPIRY_MINUTES: "30"
  REFRESH_TOKEN_EXPIRY_DAYS: "7"
  MAX_LOGIN_ATTEMPTS: "5"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  
  # Monitoring Configuration
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Feature Flags
  ENABLE_BETA_FEATURES: "false"
  ENABLE_ADVANCED_ANALYTICS: "true"
  ENABLE_PDF_EXPORT: "true"
  ENABLE_WEBSOCKET: "true"
  
  # External Services
  ENABLE_BACKUP: "true"
  BACKUP_INTERVAL_HOURS: "6"
  ENABLE_ALERTING: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  namespace: production
  labels:
    app: financial-planner-ml
    component: config
data:
  # ML Model Configuration
  MODEL_CACHE_SIZE: "1000"
  MODEL_BATCH_SIZE: "32"
  MODEL_TIMEOUT_SECONDS: "60"
  
  # GPU Configuration
  CUDA_VISIBLE_DEVICES: "0"
  GPU_MEMORY_FRACTION: "0.8"
  
  # Training Configuration
  TRAINING_ENABLED: "false"
  MODEL_UPDATE_INTERVAL_HOURS: "24"
  
  # Risk Model Configuration
  RISK_LOOKBACK_DAYS: "252"
  VOLATILITY_WINDOW: "30"
  CORRELATION_THRESHOLD: "0.8"
  
  # Portfolio Optimization
  OPTIMIZATION_METHOD: "mean_variance"
  REBALANCING_THRESHOLD: "0.05"
  MAX_ALLOCATION_SINGLE_ASSET: "0.3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring
  labels:
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
      
      - job_name: 'financial-planner-api'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - production
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: financial-planner-api
        - source_labels: [__address__]
          regex: ([^:]+)(?::\d+)?
          target_label: __address__
          replacement: $1:9090
      
      - job_name: 'financial-planner-worker'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - production
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: financial-planner-worker
        - source_labels: [__address__]
          regex: ([^:]+)(?::\d+)?
          target_label: __address__
          replacement: $1:9540
  
  grafana-datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-service:16686
    - name: Elasticsearch
      type: elasticsearch
      access: proxy
      url: http://elasticsearch-service:9200
      database: "logstash-*"