filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/*.log
    - /logs/**/*.log
  fields:
    service: financial-planner
    environment: production
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after
  json.keys_under_root: true
  json.add_error_key: true

- type: container
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch-service:9200"]
  index: "financial-planner-logs-%{+yyyy.MM.dd}"
  template.name: "financial-planner"
  template.pattern: "financial-planner-*"

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_kubernetes_metadata:
    host: ${NODE_NAME}
    matchers:
    - logs_path:
        logs_path: "/var/log/containers/"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

monitoring.enabled: true