apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-planning-api
  namespace: financial-planning-prod
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "2000m"
            ephemeral-storage: "4Gi"
        env:
        - name: WORKERS
          value: "8"
        - name: MAX_CONNECTIONS
          value: "2000"
      nodeSelector:
        kubernetes.io/arch: amd64
        node.kubernetes.io/instance-type: m5.xlarge
        node-role.kubernetes.io/worker: ""
      tolerations:
      - key: "production-workload"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"