global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'financial-planning'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI Application
  - job_name: 'financial-planning-api'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']
    scrape_timeout: 5s
    honor_labels: true

  # PostgreSQL Database
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Nginx for web server metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Blackbox exporter for synthetic monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://your-domain.com/health
        - https://your-domain.com/api/v1/health
        - https://your-domain.com/api/v1/market-data/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom financial planning metrics
  - job_name: 'financial-metrics'
    scrape_interval: 30s
    metrics_path: /api/v1/metrics/business
    static_configs:
      - targets: ['app:8000']