apiVersion: v1
kind: Service
metadata:
  name: financial-planning-api
  namespace: financial-planning
  labels:
    app: financial-planning-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "3"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: financial-planning-api
  sessionAffinity: None

---
apiVersion: v1
kind: Service  
metadata:
  name: financial-planning-api-headless
  namespace: financial-planning
  labels:
    app: financial-planning-api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: financial-planning-api

---
# Blue-Green deployment services
apiVersion: v1
kind: Service
metadata:
  name: financial-planning-api-blue
  namespace: financial-planning
  labels:
    app: financial-planning-api
    version: blue
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: financial-planning-api
    version: blue

---
apiVersion: v1
kind: Service
metadata:
  name: financial-planning-api-green
  namespace: financial-planning
  labels:
    app: financial-planning-api
    version: green
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: financial-planning-api
    version: green