apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-planning-api
  namespace: financial-planning
  labels:
    app: financial-planning-api
  annotations:
    # AWS IAM role for service account (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/financial-planning-api-role
    # Azure AD Workload Identity
    azure.workload.identity/client-id: "your-client-id"
    # Google Cloud Workload Identity
    iam.gke.io/gcp-service-account: financial-planning-api@PROJECT-ID.iam.gserviceaccount.com
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-planning-api-role
  namespace: financial-planning
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: financial-planning-api-binding
  namespace: financial-planning
subjects:
- kind: ServiceAccount
  name: financial-planning-api
  namespace: financial-planning
roleRef:
  kind: Role
  name: financial-planning-api-role
  apiGroup: rbac.authorization.k8s.io